/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#define SYSCTL *((volatile unsigned long*) 0x400fe108)

#define GPIO_PORTF_DIR_R *((volatile unsigned long*) 0x40025400)
#define GPIO_PORTF_DEN_R *((volatile unsigned long*) 0x4002551c)
#define GPIO_PORTF_DATA_R *((volatile unsigned long*) 0x400253fc)

int main(){
	SYSCTL=0x20;
	//delay to make sure GPIO is up and running
	for(volatile unsigned long delay_count = 0; delay_count<200;delay_count++){
	};
	GPIO_PORTF_DIR_R |= 1<<3;
	GPIO_PORTF_DEN_R |= 1<<3;
	while(1){
		GPIO_PORTF_DATA_R |=1<<3;
		for(volatile unsigned long delay_count = 0; delay_count<200000;delay_count++){
		};
		GPIO_PORTF_DATA_R &=~(1<<3);
		for(volatile unsigned long delay_count = 0; delay_count<200000;delay_count++){
		};
	}
	
	
	
	return 0;
}