/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)

#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE + 0x08)

#define RCC_BASE 0x40021000
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)

#define declare1(reg,val,shift) reg &= ~(1<<shift);reg |= (val<<shift);
#define declare2(reg,val,shift) reg &= ~(11<<shift);reg |= (val<<shift);
#define declare3(reg,val,shift) reg &= ~(111<<shift);reg |= (val<<shift);
#define declare4(reg,val,shift) reg &= ~(1111<<shift);reg |= (val<<shift);

void RCC_INIT(){
	declare2(RCC_APB2ENR,0b11,2);
}
void GPIO_INIT(){
	declare4(GPIOA_CRL,0b0100,4);
	declare4(GPIOA_CRH,0b0100,20);
	declare4(GPIOB_CRL,0b0001,4);
	declare4(GPIOB_CRH,0b0001,20);
}
int main(void)
{
	RCC_INIT();
	GPIO_INIT();
	declare1(GPIOB_ODR,0b1,1);
	for(int i  = 0 ; i < 5000; i++);
	declare1(GPIOB_ODR,0b1,13);
	for(int i  = 0 ; i < 5000; i++);

    while(1){
    	if(((GPIOA_IDR&(1<<1))>>1)==0){
    		GPIOB_ODR ^= 1<<1;
    		while(((GPIOA_IDR&(1<<1))>>1)==0);
    	}
    	if(((GPIOA_IDR&(1<<13))>>13)==1){
    	    		GPIOB_ODR ^= 1<<13;
    	    	}
    	for(int i  = 0 ; i < 5000; i++);
    }
}
